services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./personal_assistant/.env
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - personal-assistant-web_data:/var/lib/postgresql/data


  django:
    build:
      context: ./personal_assistant
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - ./personal_assistant/.env


volumes:
  personal-assistant-web_data:

networks:
  app-network:
    driver: bridge